"""Abstract interfaces (protocols) for cross-package contracts."""

from __future__ import annotations

from typing import Protocol, runtime_checkable
from uuid import UUID

from packages.core.models import Opportunity, WorkerProfile


@runtime_checkable
class Repository[T](Protocol):
    """Generic async CRUD repository."""

    async def get(self, id: UUID) -> T | None: ...
    async def list(self, *, limit: int = 100, offset: int = 0) -> list[T]: ...
    async def create(self, entity: T) -> T: ...
    async def update(self, id: UUID, entity: T) -> T: ...
    async def delete(self, id: UUID) -> bool: ...


@runtime_checkable
class OpportunityRepository(Protocol):
    async def get(self, id: UUID) -> Opportunity | None: ...
    async def list(self, *, limit: int = 100, offset: int = 0) -> list[Opportunity]: ...
    async def create(self, entity: Opportunity) -> Opportunity: ...
    async def search_by_skills(self, skills: list[str], *, limit: int = 20) -> list[Opportunity]: ...


@runtime_checkable
class WorkerRepository(Protocol):
    async def get(self, id: UUID) -> WorkerProfile | None: ...
    async def list(self, *, limit: int = 100, offset: int = 0) -> list[WorkerProfile]: ...
    async def create(self, entity: WorkerProfile) -> WorkerProfile: ...


@runtime_checkable
class VectorStore(Protocol):
    """Async vector-store interface for semantic search."""

    async def upsert(self, collection: str, id: str, vector: list[float], payload: dict) -> None: ...
    async def search(
        self, collection: str, vector: list[float], *, limit: int = 10
    ) -> list[dict]: ...
